"""changes mapped column models

Revision ID: 82827e30a2c0
Revises: 49d5cb232a9b
Create Date: 2025-11-01 23:35:19.530292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82827e30a2c0'
down_revision = '49d5cb232a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###
